"""Prompt templates for LLM operations.

Each prompt pair consists of:
- *_SYSTEM: Instructions for the system role (trusted, no external data)
- *_DATA: Template for the user role (formatted with external data)

External data in user messages is wrapped in <external_data> tags.
The system prompt instructs the model to never follow instructions within those tags.
"""

from app.llm.prompts.lead import (
    EVALUATE_LEAD_QUALITY_DATA,
    EVALUATE_LEAD_QUALITY_SYSTEM,
    SUMMARIZE_BUSINESS_DATA,
    SUMMARIZE_BUSINESS_SYSTEM,
)
from app.llm.prompts.outreach import (
    GENERATE_OUTREACH_EMAIL_DATA,
    GENERATE_OUTREACH_EMAIL_SYSTEM,
    GENERATE_WHATSAPP_DRAFT_DATA,
    GENERATE_WHATSAPP_DRAFT_SYSTEM,
)
from app.llm.prompts.reply import (
    CLASSIFY_INBOUND_REPLY_DATA,
    CLASSIFY_INBOUND_REPLY_SYSTEM,
    GENERATE_REPLY_ASSISTANT_DRAFT_DATA,
    GENERATE_REPLY_ASSISTANT_DRAFT_SYSTEM,
)
from app.llm.prompts.research import (
    COMMERCIAL_BRIEF_DATA,
    COMMERCIAL_BRIEF_SYSTEM,
    DOSSIER_DATA,
    DOSSIER_SYSTEM,
)
from app.llm.prompts.review import (
    BATCH_REVIEW_SYNTHESIS_DATA,
    BATCH_REVIEW_SYNTHESIS_SYSTEM,
    BATCH_REVIEW_VALIDATION_DATA,
    BATCH_REVIEW_VALIDATION_SYSTEM,
    REVIEW_COMMERCIAL_BRIEF_DATA,
    REVIEW_COMMERCIAL_BRIEF_SYSTEM,
    REVIEW_INBOUND_REPLY_DATA,
    REVIEW_INBOUND_REPLY_SYSTEM,
    REVIEW_LEAD_DATA,
    REVIEW_LEAD_SYSTEM,
    REVIEW_OUTREACH_DRAFT_DATA,
    REVIEW_OUTREACH_DRAFT_SYSTEM,
    REVIEW_REPLY_ASSISTANT_DRAFT_DATA,
    REVIEW_REPLY_ASSISTANT_DRAFT_SYSTEM,
)
from app.llm.prompts.system import (
    ANTI_INJECTION_PREAMBLE,
    CLOSER_RESPONSE_SYSTEM,
)

__all__ = [
    "ANTI_INJECTION_PREAMBLE",
    "CLOSER_RESPONSE_SYSTEM",
    "SUMMARIZE_BUSINESS_SYSTEM",
    "SUMMARIZE_BUSINESS_DATA",
    "EVALUATE_LEAD_QUALITY_SYSTEM",
    "EVALUATE_LEAD_QUALITY_DATA",
    "GENERATE_OUTREACH_EMAIL_SYSTEM",
    "GENERATE_OUTREACH_EMAIL_DATA",
    "GENERATE_WHATSAPP_DRAFT_SYSTEM",
    "GENERATE_WHATSAPP_DRAFT_DATA",
    "CLASSIFY_INBOUND_REPLY_SYSTEM",
    "CLASSIFY_INBOUND_REPLY_DATA",
    "GENERATE_REPLY_ASSISTANT_DRAFT_SYSTEM",
    "GENERATE_REPLY_ASSISTANT_DRAFT_DATA",
    "DOSSIER_SYSTEM",
    "DOSSIER_DATA",
    "COMMERCIAL_BRIEF_SYSTEM",
    "COMMERCIAL_BRIEF_DATA",
    "REVIEW_LEAD_SYSTEM",
    "REVIEW_LEAD_DATA",
    "REVIEW_OUTREACH_DRAFT_SYSTEM",
    "REVIEW_OUTREACH_DRAFT_DATA",
    "REVIEW_INBOUND_REPLY_SYSTEM",
    "REVIEW_INBOUND_REPLY_DATA",
    "REVIEW_REPLY_ASSISTANT_DRAFT_SYSTEM",
    "REVIEW_REPLY_ASSISTANT_DRAFT_DATA",
    "REVIEW_COMMERCIAL_BRIEF_SYSTEM",
    "REVIEW_COMMERCIAL_BRIEF_DATA",
    "BATCH_REVIEW_SYNTHESIS_SYSTEM",
    "BATCH_REVIEW_SYNTHESIS_DATA",
    "BATCH_REVIEW_VALIDATION_SYSTEM",
    "BATCH_REVIEW_VALIDATION_DATA",
]
