"""add partial unique index on outreach_deliveries for double-send prevention

Revision ID: 3d2cd2387bc3
Revises: 9d4e1a2b7c3d
Create Date: 2026-03-14 19:37:09.091582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2cd2387bc3'
down_revision: Union[str, None] = '9d4e1a2b7c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_outreach_deliveries_active_or_sent_per_draft', 'outreach_deliveries', ['draft_id'], unique=True, postgresql_where=sa.text("status IN ('sending', 'sent')"), sqlite_where=sa.text("status IN ('sending', 'sent')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_outreach_deliveries_active_or_sent_per_draft', table_name='outreach_deliveries', postgresql_where=sa.text("status IN ('sending', 'sent')"), sqlite_where=sa.text("status IN ('sending', 'sent')"))
    # ### end Alembic commands ###
