"""add telegram_audit_log table

Revision ID: 5afc0aaf6860
Revises: f569b0ecd9af
Create Date: 2026-03-15 23:31:36.200789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5afc0aaf6860'
down_revision: Union[str, None] = 'f569b0ecd9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='telegramdirection'), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tg_audit_chat_id', 'telegram_audit_log', ['chat_id'], unique=False)
    op.create_index('ix_tg_audit_created_at', 'telegram_audit_log', ['created_at'], unique=False)
    op.create_index('ix_tg_audit_direction', 'telegram_audit_log', ['direction'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tg_audit_direction', table_name='telegram_audit_log')
    op.drop_index('ix_tg_audit_created_at', table_name='telegram_audit_log')
    op.drop_index('ix_tg_audit_chat_id', table_name='telegram_audit_log')
    op.drop_table('telegram_audit_log')
    # ### end Alembic commands ###
