"""add signature_is_solo to settings

Revision ID: 5e607b7a54b4
Revises: b71498a9548a
Create Date: 2026-03-23 18:49:59.340497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e607b7a54b4'
down_revision: Union[str, None] = 'b71498a9548a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('operational_settings', sa.Column('signature_is_solo', sa.Boolean(), server_default=sa.text('false'), nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_settings', 'signature_is_solo')
    # ### end Alembic commands ###
