"""add whatsapp_audit_log

Revision ID: 5fddff92305a
Revises: 78f91948b49b
Create Date: 2026-03-14 20:26:42.000530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fddff92305a'
down_revision: Union[str, None] = '78f91948b49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.Enum('in', 'out', name='messagedirection'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wa_audit_created_at', 'whatsapp_audit_log', ['created_at'], unique=False)
    op.create_index('ix_wa_audit_direction', 'whatsapp_audit_log', ['direction'], unique=False)
    op.create_index('ix_wa_audit_phone', 'whatsapp_audit_log', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wa_audit_phone', table_name='whatsapp_audit_log')
    op.drop_index('ix_wa_audit_direction', table_name='whatsapp_audit_log')
    op.drop_index('ix_wa_audit_created_at', table_name='whatsapp_audit_log')
    op.drop_table('whatsapp_audit_log')
    # ### end Alembic commands ###
