"""add composite indexes on leads

Revision ID: 64d90f18d551
Revises: 5e607b7a54b4
Create Date: 2026-03-23 21:43:09.997442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64d90f18d551'
down_revision: Union[str, None] = '5e607b7a54b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_leads_created_at', 'leads', ['created_at'], unique=False)
    op.create_index('ix_leads_llm_quality', 'leads', ['llm_quality'], unique=False)
    op.create_index('ix_leads_status_score', 'leads', ['status', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leads_status_score', table_name='leads')
    op.drop_index('ix_leads_llm_quality', table_name='leads')
    op.drop_index('ix_leads_created_at', table_name='leads')
    # ### end Alembic commands ###
