"""add batch_reviews and improvement_proposals tables

Revision ID: 694f94aae1c8
Revises: j4d5e6f7g8h9
Create Date: 2026-04-05 22:07:35.000420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '694f94aae1c8'
down_revision: Union[str, None] = 'j4d5e6f7g8h9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # -- Batch review tables (not auto-detected) --
    op.create_table(
        'batch_reviews',
        sa.Column('id', sa.Uuid(), nullable=False, default=sa.text('gen_random_uuid()')),
        sa.Column('trigger_reason', sa.String(50), nullable=False),
        sa.Column('batch_size', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
        sa.Column('executor_draft', sa.Text(), nullable=True),
        sa.Column('reviewer_verdict', sa.String(32), nullable=True),
        sa.Column('reviewer_notes', sa.Text(), nullable=True),
        sa.Column('strategy_brief', sa.Text(), nullable=True),
        sa.Column('metrics_json', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(32), nullable=False, server_default='generating'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'improvement_proposals',
        sa.Column('id', sa.Uuid(), nullable=False, default=sa.text('gen_random_uuid()')),
        sa.Column('batch_review_id', sa.Uuid(), nullable=False),
        sa.Column('category', sa.String(50), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('impact', sa.String(20), nullable=False, server_default='medium'),
        sa.Column('confidence', sa.String(20), nullable=False, server_default='medium'),
        sa.Column('evidence_summary', sa.Text(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('approved_by', sa.String(50), nullable=True),
        sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('result_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['batch_review_id'], ['batch_reviews.id'], ondelete='CASCADE'),
    )

    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_artifacts_lead_id'), table_name='artifacts')
    op.alter_column('investigation_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lead_research_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('lead_research_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('leads_source_id_fkey'), 'leads', type_='foreignkey')
    op.create_foreign_key(None, 'leads', 'lead_sources', ['source_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('messages_conversation_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('operational_settings', sa.Column('low_resource_mode', sa.Boolean(), nullable=True))
    op.alter_column('outbound_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbound_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outcome_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_outreach_drafts_generated_at'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_outreach_drafts_status'), table_name='outreach_drafts')
    op.drop_index(op.f('ix_outreach_logs_created_at'), table_name='outreach_logs')
    op.create_index('ix_outreach_logs_draft_id', 'outreach_logs', ['draft_id'], unique=False)
    op.alter_column('review_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('tool_calls_message_id_fkey'), 'tool_calls', type_='foreignkey')
    op.create_foreign_key(None, 'tool_calls', 'messages', ['message_id'], ['id'], ondelete='CASCADE')
    op.alter_column('weekly_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('weekly_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'tool_calls', type_='foreignkey')
    op.create_foreign_key(op.f('tool_calls_message_id_fkey'), 'tool_calls', 'messages', ['message_id'], ['id'])
    op.alter_column('review_corrections', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_outreach_logs_draft_id', table_name='outreach_logs')
    op.create_index(op.f('ix_outreach_logs_created_at'), 'outreach_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_status'), 'outreach_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_outreach_drafts_generated_at'), 'outreach_drafts', ['generated_at'], unique=False)
    op.alter_column('outcome_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbound_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('outbound_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('operational_settings', 'low_resource_mode')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_conversation_id_fkey'), 'messages', 'conversations', ['conversation_id'], ['id'])
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.create_foreign_key(op.f('leads_source_id_fkey'), 'leads', 'lead_sources', ['source_id'], ['id'])
    op.alter_column('lead_research_reports', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('lead_research_reports', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('investigation_threads', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_artifacts_lead_id'), 'artifacts', ['lead_id'], unique=False)
    op.alter_column('artifacts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
