"""add openclaw config fields

Revision ID: 76d4256f1920
Revises: e7a3f1b2c4d5
Create Date: 2026-03-14 23:46:41.550914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d4256f1920'
down_revision: Union[str, None] = 'e7a3f1b2c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operational_settings', sa.Column('openclaw_model', sa.String(), server_default='leader', nullable=False))
    op.add_column('operational_settings', sa.Column('openclaw_max_response_chars', sa.Integer(), server_default='600', nullable=False))
    op.add_column('operational_settings', sa.Column('openclaw_rate_limit', sa.Integer(), server_default='20', nullable=False))
    op.add_column('operational_settings', sa.Column('openclaw_rate_window_seconds', sa.Integer(), server_default='900', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_settings', 'openclaw_rate_window_seconds')
    op.drop_column('operational_settings', 'openclaw_rate_limit')
    op.drop_column('operational_settings', 'openclaw_max_response_chars')
    op.drop_column('operational_settings', 'openclaw_model')
    # ### end Alembic commands ###
