"""add notifications whatsapp_credentials and operational settings notification fields

Revision ID: 78f91948b49b
Revises: 3d2cd2387bc3
Create Date: 2026-03-14 20:06:14.804980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f91948b49b'
down_revision: Union[str, None] = '3d2cd2387bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('business', 'system', 'security', name='notificationcategory'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'high', 'critical', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('source_kind', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('unread', 'read', 'acknowledged', 'resolved', name='notificationstatus'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channel_state', sa.JSON(), nullable=True),
    sa.Column('dedup_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_category', 'notifications', ['category'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_severity', 'notifications', ['severity'], unique=False)
    op.create_index('ix_notifications_source', 'notifications', ['source_kind', 'source_id'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['type'], unique=False)
    op.create_index('uq_notifications_dedup_key', 'notifications', ['dedup_key'], unique=True)
    op.create_table('whatsapp_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('operational_settings', sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('operational_settings', sa.Column('notification_score_threshold', sa.Integer(), nullable=False, server_default=sa.text('70')))
    op.add_column('operational_settings', sa.Column('whatsapp_alerts_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('operational_settings', sa.Column('whatsapp_min_severity', sa.String(), nullable=False, server_default=sa.text("'high'")))
    op.add_column('operational_settings', sa.Column('whatsapp_categories', sa.JSON(), nullable=False, server_default=sa.text("'[\"business\", \"security\"]'")))
    op.add_column('operational_settings', sa.Column('whatsapp_openclaw_enrichment', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('operational_settings', sa.Column('whatsapp_conversational_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('operational_settings', sa.Column('whatsapp_actions_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_settings', 'whatsapp_actions_enabled')
    op.drop_column('operational_settings', 'whatsapp_conversational_enabled')
    op.drop_column('operational_settings', 'whatsapp_openclaw_enrichment')
    op.drop_column('operational_settings', 'whatsapp_categories')
    op.drop_column('operational_settings', 'whatsapp_min_severity')
    op.drop_column('operational_settings', 'whatsapp_alerts_enabled')
    op.drop_column('operational_settings', 'notification_score_threshold')
    op.drop_column('operational_settings', 'notifications_enabled')
    op.drop_table('whatsapp_credentials')
    op.drop_index('uq_notifications_dedup_key', table_name='notifications')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_source', table_name='notifications')
    op.drop_index('ix_notifications_severity', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
