"""initial_schema

Revision ID: 955a04d99157
Revises: 
Create Date: 2026-03-12 15:20:22.573108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955a04d99157'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('MANUAL', 'CRAWLER', 'IMPORT', name='sourcetype'), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppression_list',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('business_name', sa.String(length=500), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('instagram_url', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'ENRICHED', 'SCORED', 'DRAFT_READY', 'APPROVED', 'CONTACTED', 'SUPPRESSED', name='leadstatus'), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('llm_summary', sa.Text(), nullable=True),
    sa.Column('llm_quality_assessment', sa.Text(), nullable=True),
    sa.Column('llm_suggested_angle', sa.Text(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['lead_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedup_hash')
    )
    op.create_index('ix_leads_email', 'leads', ['email'], unique=False)
    op.create_index('ix_leads_score', 'leads', ['score'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_index('ix_leads_website_url', 'leads', ['website_url'], unique=False)
    op.create_table('lead_signals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('signal_type', sa.Enum('NO_WEBSITE', 'INSTAGRAM_ONLY', 'OUTDATED_WEBSITE', 'NO_CUSTOM_DOMAIN', 'NO_VISIBLE_EMAIL', 'NO_SSL', 'WEAK_SEO', 'NO_MOBILE_FRIENDLY', 'SLOW_LOAD', 'HAS_WEBSITE', 'HAS_CUSTOM_DOMAIN', name='signaltype'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SENT', name='draftstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outreach_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('GENERATED', 'REVIEWED', 'APPROVED', 'REJECTED', 'SENT', name='logaction'), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['outreach_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_logs')
    op.drop_table('outreach_drafts')
    op.drop_table('lead_signals')
    op.drop_index('ix_leads_website_url', table_name='leads')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_score', table_name='leads')
    op.drop_index('ix_leads_email', table_name='leads')
    op.drop_table('leads')
    op.drop_table('suppression_list')
    op.drop_table('lead_sources')
    # ### end Alembic commands ###
