"""add webhook_secret to whatsapp_credentials

Revision ID: a5cc6250a134
Revises: 76d4256f1920
Create Date: 2026-03-14 23:54:19.695418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cc6250a134'
down_revision: Union[str, None] = '76d4256f1920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_credentials', sa.Column('webhook_secret', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_credentials', 'webhook_secret')
    # ### end Alembic commands ###
