"""add_lat_lng_to_leads

Revision ID: b06815d91943
Revises: b2c3d4e5f6a7
Create Date: 2026-03-15 03:39:39.675224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06815d91943'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'longitude')
    op.drop_column('leads', 'latitude')
    # ### end Alembic commands ###
