"""add llm_quality to leads

Revision ID: b71498a9548a
Revises: 5afc0aaf6860
Create Date: 2026-03-23 18:39:27.608188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b71498a9548a'
down_revision: Union[str, None] = '5afc0aaf6860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('llm_quality', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'llm_quality')
    # ### end Alembic commands ###
