"""add_telegram_credentials_and_settings

Revision ID: f569b0ecd9af
Revises: b06815d91943
Create Date: 2026-03-15 23:09:55.479005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f569b0ecd9af'
down_revision: Union[str, None] = 'b06815d91943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_username', sa.String(length=100), nullable=True),
    sa.Column('bot_token', sa.String(length=500), nullable=True),
    sa.Column('chat_id', sa.String(length=50), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_secret', sa.String(length=256), nullable=True),
    sa.Column('last_test_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('operational_settings', sa.Column('telegram_alerts_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('operational_settings', sa.Column('telegram_openclaw_enrichment', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('operational_settings', sa.Column('telegram_conversational_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('operational_settings', sa.Column('telegram_actions_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operational_settings', 'telegram_actions_enabled')
    op.drop_column('operational_settings', 'telegram_conversational_enabled')
    op.drop_column('operational_settings', 'telegram_openclaw_enrichment')
    op.drop_column('operational_settings', 'telegram_alerts_enabled')
    op.drop_table('telegram_credentials')
    # ### end Alembic commands ###
