// AUTO-GENERATED by scripts/sync-enums.py — do not edit manually.
// Source of truth: app/models/lead.py, app/models/lead_signal.py
// Generated at: 2026-04-13T13:14:36Z

export type LeadStatus =
  | "new"
  | "enriched"
  | "scored"
  | "qualified"
  | "draft_ready"
  | "approved"
  | "contacted"
  | "opened"
  | "replied"
  | "meeting"
  | "won"
  | "lost"
  | "suppressed";

export const LEAD_STATUS_VALUES = ["new", "enriched", "scored", "qualified", "draft_ready", "approved", "contacted", "opened", "replied", "meeting", "won", "lost", "suppressed"] as const;

export type LeadQuality =
  | "high"
  | "medium"
  | "low"
  | "unknown";

export const LEAD_QUALITY_VALUES = ["high", "medium", "low", "unknown"] as const;

export type SignalType =
  | "no_website"
  | "instagram_only"
  | "outdated_website"
  | "no_custom_domain"
  | "no_visible_email"
  | "no_ssl"
  | "weak_seo"
  | "no_mobile_friendly"
  | "slow_load"
  | "website_error"
  | "has_website"
  | "has_custom_domain";

export const SIGNAL_TYPE_VALUES = ["no_website", "instagram_only", "outdated_website", "no_custom_domain", "no_visible_email", "no_ssl", "weak_seo", "no_mobile_friendly", "slow_load", "website_error", "has_website", "has_custom_domain"] as const;
