#!/usr/bin/env python3
"""
Generate dashboard/lib/generated-proxy-prefixes.ts from FastAPI route registration.

Source: app/api/router.py  (reads prefixes statically — no DB connection required)

Usage:
    .venv/bin/python scripts/sync-proxy-allowlist.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROUTER_FILE = REPO_ROOT / "app" / "api" / "router.py"
OUTPUT_FILE = REPO_ROOT / "dashboard" / "lib" / "generated-proxy-prefixes.ts"

# Match lines like:  from app.api.v1.foo import router as foo_router
IMPORT_RE = re.compile(r"^from\s+(app\.api\.v1\.\S+)\s+import\s+router", re.MULTILINE)

# Match lines like:  router = APIRouter(prefix="/some-prefix", ...)
PREFIX_RE = re.compile(r'APIRouter\s*\([^)]*prefix\s*=\s*["\']([^"\']+)["\']')


def collect_prefixes() -> list[str]:
    """Parse router.py imports, then read each module for its prefix."""
    router_src = ROUTER_FILE.read_text()

    modules = IMPORT_RE.findall(router_src)
    if not modules:
        print("ERROR: no router imports found in", ROUTER_FILE, file=sys.stderr)
        sys.exit(1)

    prefixes: set[str] = set()
    for dotted in modules:
        # Convert dotted module path to file path
        rel = dotted.replace(".", "/")
        candidates = [
            REPO_ROOT / f"{rel}.py",
            REPO_ROOT / rel / "__init__.py",
        ]
        src_file = next((c for c in candidates if c.exists()), None)
        if src_file is None:
            print(f"WARNING: could not find module file for {dotted}", file=sys.stderr)
            continue

        src = src_file.read_text()
        m = PREFIX_RE.search(src)
        if m:
            # Strip leading slash, add trailing slash → "leads/"
            prefix = m.group(1).lstrip("/") + "/"
            prefixes.add(prefix)
        else:
            print(f"WARNING: no APIRouter prefix found in {src_file}", file=sys.stderr)

    return sorted(prefixes)


def write_ts(prefixes: list[str]) -> None:
    lines = ['  "' + p + '",' for p in prefixes]
    body = "\n".join(lines)
    content = (
        "// AUTO-GENERATED by scripts/sync-proxy-allowlist.py — do not edit manually.\n"
        "// Source: FastAPI route registration in app/api/router.py\n"
        "export const ALLOWED_PREFIXES = [\n"
        f"{body}\n"
        "] as const;\n"
    )
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(content)
    print(f"Written {len(prefixes)} prefixes to {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    for p in prefixes:
        print(f"  {p}")


if __name__ == "__main__":
    prefixes = collect_prefixes()
    write_ts(prefixes)
