#!/usr/bin/env python3
"""Generate TypeScript enum types from Python StrEnum definitions.

Eliminates manual Python-TypeScript type mirrors by reading the Python
StrEnums and writing a single generated TypeScript file.

Usage:
    .venv/bin/python scripts/sync-enums.py
"""

from __future__ import annotations

import sys
from datetime import UTC, datetime
from pathlib import Path

# Ensure repo root is on sys.path so we can import app.models
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from app.models.lead import LeadQuality, LeadStatus  # noqa: E402
from app.models.lead_signal import SignalType  # noqa: E402

OUTPUT_FILE = REPO_ROOT / "dashboard" / "types" / "generated-enums.ts"

# Each entry: (TypeScript type name, TypeScript const array name, Python enum class, source file)
ENUM_REGISTRY: list[tuple[str, str, type, str]] = [
    ("LeadStatus", "LEAD_STATUS_VALUES", LeadStatus, "app/models/lead.py"),
    ("LeadQuality", "LEAD_QUALITY_VALUES", LeadQuality, "app/models/lead.py"),
    ("SignalType", "SIGNAL_TYPE_VALUES", SignalType, "app/models/lead_signal.py"),
]


def _generate_block(type_name: str, const_name: str, enum_cls: type) -> str:
    """Generate a union type and const array for a single enum."""
    values = [member.value for member in enum_cls]
    union_parts = "\n  | ".join(f'"{v}"' for v in values)
    array_items = ", ".join(f'"{v}"' for v in values)
    return (
        f"export type {type_name} =\n"
        f"  | {union_parts};\n"
        f"\n"
        f"export const {const_name} = [{array_items}] as const;\n"
    )


def generate() -> str:
    """Generate the full TypeScript file content."""
    source_files = sorted({entry[3] for entry in ENUM_REGISTRY})
    sources_comment = ", ".join(source_files)

    blocks = []
    for type_name, const_name, enum_cls, _source in ENUM_REGISTRY:
        blocks.append(_generate_block(type_name, const_name, enum_cls))

    body = "\n".join(blocks)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [
        "// AUTO-GENERATED by scripts/sync-enums.py \u2014 do not edit manually.",
        f"// Source of truth: {sources_comment}",
        f"// Generated at: {timestamp}",
        "",
        body,
    ]
    return "\n".join(lines)


def main() -> None:
    content = generate()
    OUTPUT_FILE.write_text(content)
    print(f"Generated {OUTPUT_FILE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
