"""Batch review — periodic AI team synthesis triggered by evidence thresholds.

Generated by Executor (analysis) + Reviewer (validation). Produces a
StrategyBrief for Mote and ranked ImprovementProposals requiring approval.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import JSON, DateTime, ForeignKey, Integer, String, Text, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class BatchReview(Base):
    __tablename__ = "batch_reviews"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    trigger_reason: Mapped[str] = mapped_column(String(50), nullable=False)
    batch_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    period_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    period_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    executor_draft: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewer_verdict: Mapped[str | None] = mapped_column(String(32), nullable=True)
    reviewer_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    strategy_brief: Mapped[str | None] = mapped_column(Text, nullable=True)
    metrics_json: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="generating")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    proposals: Mapped[list[ImprovementProposal]] = relationship(
        back_populates="batch_review", cascade="all, delete-orphan"
    )


class ImprovementProposal(Base):
    __tablename__ = "improvement_proposals"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    batch_review_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("batch_reviews.id", ondelete="CASCADE"), nullable=False
    )
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    impact: Mapped[str] = mapped_column(String(20), nullable=False, default="medium")
    confidence: Mapped[str] = mapped_column(String(20), nullable=False, default="medium")
    evidence_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="pending")
    approved_by: Mapped[str | None] = mapped_column(String(50), nullable=True)
    applied_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    result_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())

    batch_review: Mapped[BatchReview] = relationship(back_populates="proposals")
